version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: ielts-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ielts_analytics
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27000:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ielts-bot:
    build: .
    container_name: ielts-telegram-bot
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-meta-llama/llama-3.1-8b-instruct:free}
      - OPENROUTER_BASE_URL=${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}
      - OPENROUTER_SITE_URL=${OPENROUTER_SITE_URL:-https://ielts-telegram-bot.local}
      - OPENROUTER_SITE_NAME=${OPENROUTER_SITE_NAME:-IELTS Writing Bot}
      - DB_POOL_SIZE=${DB_POOL_SIZE:-10}
      - DB_MAX_OVERFLOW=${DB_MAX_OVERFLOW:-20}
      - DB_POOL_RECYCLE=${DB_POOL_RECYCLE:-3600}
      - DB_POOL_TIMEOUT=${DB_POOL_TIMEOUT:-30}
      - DEBUG=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_API=true
      - DAILY_SUBMISSION_LIMIT=${DAILY_SUBMISSION_LIMIT:-3}
      - PRO_DAILY_LIMIT=${PRO_DAILY_LIMIT:-50}
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - MONGODB_URL=mongodb://${MONGO_ROOT_USER:-admin}:${MONGO_ROOT_PASSWORD}@mongodb:27017/ielts_analytics?authSource=admin

volumes:
  postgres_data:
  mongodb_data: