version: '3.8'

services:
  ielts-bot:
    build: .
    container_name: ielts-telegram-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4}
      - DATABASE_URL=sqlite:///./data/ielts_bot.db
      - DEBUG=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ENABLE_API=true
      - DAILY_SUBMISSION_LIMIT=${DAILY_SUBMISSION_LIMIT:-3}
      - PRO_DAILY_LIMIT=${PRO_DAILY_LIMIT:-50}
      - API_HOST=0.0.0.0
      - API_PORT=3333
    ports:
      - "3333:3333"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"